export interface PantryItem {
  id: string;
  name: string;
  barcode?: string;
  quantity: number;
  unit: string;
  expiryDate?: string; // ISO 8601 string
  lowStockThreshold: number; // threshold for low stock alert
  userId: string;
  category: string;
  createdAt: any; // Firestore Timestamp or ISO string
  updatedAt: any;
}

export interface ShoppingItem {
  id: string;
  name: string;
  barcode?: string;
  quantity: number;
  unit: string;
  userId: string;
  checked: boolean;
  autoGenerated: boolean; // True if auto-created due to low pantry stock
  createdAt: any;
  updatedAt: any;
}

export interface ConsumptionLog {
  id: string;
  userId: string;
  itemName: string;
  quantity: number;
  action: 'consumed' | 'expired' | 'wasted' | 'purchased';
  createdAt: any;
}

export interface UserSettings {
  userId: string;
  pushNotificationsEnabled: boolean;
  lowStockAlertsEnabled: boolean;
  expiryReminderDays: number; // trigger alert X days before expiry
  updatedAt: any;
  customCategories?: string[];
}

export interface RecipeSuggestion {
  title: string;
  ingredientsUsed: string[];
  additionalIngredientsNeeded: string[];
  instructions: string[];
  estimatedTime: string;
  wasteImpactScore: number; // 1-100 indicating how well it used expiring food
}

export function parseFirestoreDate(val: any): Date {
  if (!val) return new Date();
  if (val instanceof Date) return val;
  if (typeof val.toDate === "function") return val.toDate();
  if (typeof val === "string" || typeof val === "number") return new Date(val);
  if (typeof val.seconds === "number") {
    return new Date(val.seconds * 1000 + Math.floor((val.nanoseconds || 0) / 1000000));
  }
  return new Date(val);
}

export const DEFAULT_CATEGORIES = [
  "Dairy",
  "Produce",
  "Bakery",
  "Pantry",
  "Meat & Seafood",
  "Beverages",
  "Household",
  "Frozen"
];

